[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "clt-mlmcmc"
version = "0.1.0"
description = "Coupled Landslide-Tsunami Bayesian Inference with MLMCMC"
authors = [{ name="jaamestaay" }]
dependencies = []